# fly.toml app configuration file generated for reese-bot on 2023-12-30T16:19:20-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reese-bot"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
